/**
 * This file is auto-generated by @tanstack/router-plugin on dev/build.
 * This stub exists only so the project compiles before the first dev run.
 * After running `bun run dev` or `bun run build`, it will be regenerated.
 */
import { createRootRoute } from '@tanstack/react-router';

export const routeTree = createRootRoute();
