/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWslugRouteImport } from './routes/w.$wslug'
import { Route as DevDesignSystemRouteImport } from './routes/dev.design-system'
import { Route as WWslugIndexRouteImport } from './routes/w.$wslug.index'
import { Route as WWslugTriggersRouteImport } from './routes/w.$wslug.triggers'
import { Route as WWslugSettingsRouteImport } from './routes/w.$wslug.settings'
import { Route as WWslugPPslugRouteImport } from './routes/w.$wslug.p.$pslug'
import { Route as WWslugPPslugIndexRouteImport } from './routes/w.$wslug.p.$pslug.index'
import { Route as WWslugPPslugWorkItemsRouteImport } from './routes/w.$wslug.p.$pslug.work-items'
import { Route as WWslugPPslugWikiRouteImport } from './routes/w.$wslug.p.$pslug.wiki'
import { Route as WWslugPPslugBoardRouteImport } from './routes/w.$wslug.p.$pslug.board'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWslugRoute = WWslugRouteImport.update({
  id: '/w/$wslug',
  path: '/w/$wslug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const WWslugIndexRoute = WWslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugTriggersRoute = WWslugTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugSettingsRoute = WWslugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPPslugRoute = WWslugPPslugRouteImport.update({
  id: '/p/$pslug',
  path: '/p/$pslug',
  getParentRoute: () => WWslugRoute,
} as any)
const WWslugPPslugIndexRoute = WWslugPPslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWslugPPslugRoute,
} as any)
const WWslugPPslugWorkItemsRoute = WWslugPPslugWorkItemsRouteImport.update({
  id: '/work-items',
  path: '/work-items',
  getParentRoute: () => WWslugPPslugRoute,
} as any)
const WWslugPPslugWikiRoute = WWslugPPslugWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => WWslugPPslugRoute,
} as any)
const WWslugPPslugBoardRoute = WWslugPPslugBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => WWslugPPslugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/triggers': typeof WWslugTriggersRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/p/$pslug': typeof WWslugPPslugRouteWithChildren
  '/w/$wslug/p/$pslug/board': typeof WWslugPPslugBoardRoute
  '/w/$wslug/p/$pslug/wiki': typeof WWslugPPslugWikiRoute
  '/w/$wslug/p/$pslug/work-items': typeof WWslugPPslugWorkItemsRoute
  '/w/$wslug/p/$pslug/': typeof WWslugPPslugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/triggers': typeof WWslugTriggersRoute
  '/w/$wslug': typeof WWslugIndexRoute
  '/w/$wslug/p/$pslug/board': typeof WWslugPPslugBoardRoute
  '/w/$wslug/p/$pslug/wiki': typeof WWslugPPslugWikiRoute
  '/w/$wslug/p/$pslug/work-items': typeof WWslugPPslugWorkItemsRoute
  '/w/$wslug/p/$pslug': typeof WWslugPPslugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/w/$wslug': typeof WWslugRouteWithChildren
  '/w/$wslug/settings': typeof WWslugSettingsRoute
  '/w/$wslug/triggers': typeof WWslugTriggersRoute
  '/w/$wslug/': typeof WWslugIndexRoute
  '/w/$wslug/p/$pslug': typeof WWslugPPslugRouteWithChildren
  '/w/$wslug/p/$pslug/board': typeof WWslugPPslugBoardRoute
  '/w/$wslug/p/$pslug/wiki': typeof WWslugPPslugWikiRoute
  '/w/$wslug/p/$pslug/work-items': typeof WWslugPPslugWorkItemsRoute
  '/w/$wslug/p/$pslug/': typeof WWslugPPslugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dev/design-system'
    | '/w/$wslug'
    | '/w/$wslug/settings'
    | '/w/$wslug/triggers'
    | '/w/$wslug/'
    | '/w/$wslug/p/$pslug'
    | '/w/$wslug/p/$pslug/board'
    | '/w/$wslug/p/$pslug/wiki'
    | '/w/$wslug/p/$pslug/work-items'
    | '/w/$wslug/p/$pslug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dev/design-system'
    | '/w/$wslug/settings'
    | '/w/$wslug/triggers'
    | '/w/$wslug'
    | '/w/$wslug/p/$pslug/board'
    | '/w/$wslug/p/$pslug/wiki'
    | '/w/$wslug/p/$pslug/work-items'
    | '/w/$wslug/p/$pslug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dev/design-system'
    | '/w/$wslug'
    | '/w/$wslug/settings'
    | '/w/$wslug/triggers'
    | '/w/$wslug/'
    | '/w/$wslug/p/$pslug'
    | '/w/$wslug/p/$pslug/board'
    | '/w/$wslug/p/$pslug/wiki'
    | '/w/$wslug/p/$pslug/work-items'
    | '/w/$wslug/p/$pslug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  WWslugRoute: typeof WWslugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wslug': {
      id: '/w/$wslug'
      path: '/w/$wslug'
      fullPath: '/w/$wslug'
      preLoaderRoute: typeof WWslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wslug/': {
      id: '/w/$wslug/'
      path: '/'
      fullPath: '/w/$wslug/'
      preLoaderRoute: typeof WWslugIndexRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/triggers': {
      id: '/w/$wslug/triggers'
      path: '/triggers'
      fullPath: '/w/$wslug/triggers'
      preLoaderRoute: typeof WWslugTriggersRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/settings': {
      id: '/w/$wslug/settings'
      path: '/settings'
      fullPath: '/w/$wslug/settings'
      preLoaderRoute: typeof WWslugSettingsRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/p/$pslug': {
      id: '/w/$wslug/p/$pslug'
      path: '/p/$pslug'
      fullPath: '/w/$wslug/p/$pslug'
      preLoaderRoute: typeof WWslugPPslugRouteImport
      parentRoute: typeof WWslugRoute
    }
    '/w/$wslug/p/$pslug/': {
      id: '/w/$wslug/p/$pslug/'
      path: '/'
      fullPath: '/w/$wslug/p/$pslug/'
      preLoaderRoute: typeof WWslugPPslugIndexRouteImport
      parentRoute: typeof WWslugPPslugRoute
    }
    '/w/$wslug/p/$pslug/work-items': {
      id: '/w/$wslug/p/$pslug/work-items'
      path: '/work-items'
      fullPath: '/w/$wslug/p/$pslug/work-items'
      preLoaderRoute: typeof WWslugPPslugWorkItemsRouteImport
      parentRoute: typeof WWslugPPslugRoute
    }
    '/w/$wslug/p/$pslug/wiki': {
      id: '/w/$wslug/p/$pslug/wiki'
      path: '/wiki'
      fullPath: '/w/$wslug/p/$pslug/wiki'
      preLoaderRoute: typeof WWslugPPslugWikiRouteImport
      parentRoute: typeof WWslugPPslugRoute
    }
    '/w/$wslug/p/$pslug/board': {
      id: '/w/$wslug/p/$pslug/board'
      path: '/board'
      fullPath: '/w/$wslug/p/$pslug/board'
      preLoaderRoute: typeof WWslugPPslugBoardRouteImport
      parentRoute: typeof WWslugPPslugRoute
    }
  }
}

interface WWslugPPslugRouteChildren {
  WWslugPPslugBoardRoute: typeof WWslugPPslugBoardRoute
  WWslugPPslugWikiRoute: typeof WWslugPPslugWikiRoute
  WWslugPPslugWorkItemsRoute: typeof WWslugPPslugWorkItemsRoute
  WWslugPPslugIndexRoute: typeof WWslugPPslugIndexRoute
}

const WWslugPPslugRouteChildren: WWslugPPslugRouteChildren = {
  WWslugPPslugBoardRoute: WWslugPPslugBoardRoute,
  WWslugPPslugWikiRoute: WWslugPPslugWikiRoute,
  WWslugPPslugWorkItemsRoute: WWslugPPslugWorkItemsRoute,
  WWslugPPslugIndexRoute: WWslugPPslugIndexRoute,
}

const WWslugPPslugRouteWithChildren = WWslugPPslugRoute._addFileChildren(
  WWslugPPslugRouteChildren,
)

interface WWslugRouteChildren {
  WWslugSettingsRoute: typeof WWslugSettingsRoute
  WWslugTriggersRoute: typeof WWslugTriggersRoute
  WWslugIndexRoute: typeof WWslugIndexRoute
  WWslugPPslugRoute: typeof WWslugPPslugRouteWithChildren
}

const WWslugRouteChildren: WWslugRouteChildren = {
  WWslugSettingsRoute: WWslugSettingsRoute,
  WWslugTriggersRoute: WWslugTriggersRoute,
  WWslugIndexRoute: WWslugIndexRoute,
  WWslugPPslugRoute: WWslugPPslugRouteWithChildren,
}

const WWslugRouteWithChildren =
  WWslugRoute._addFileChildren(WWslugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DevDesignSystemRoute: DevDesignSystemRoute,
  WWslugRoute: WWslugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
