export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  STATUS_NOT_FOUND: 'STATUS_NOT_FOUND',
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',
  VIEW_NOT_FOUND: 'VIEW_NOT_FOUND',
  SLUG_CONFLICT: 'SLUG_CONFLICT',
  STATUS_IN_USE: 'STATUS_IN_USE',
  BUILTIN_TRIGGER_LOCKED: 'BUILTIN_TRIGGER_LOCKED',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_FILTER: 'INVALID_FILTER',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
