#!/usr/bin/env bun
// The real single-binary build (Audit H1). Produces dist/folio — a self-contained
// executable that serves the React bundle AND runs boot migrations with NO files
// on disk beside it.
//
// How: `bun build --compile` embeds any file imported via a static top-level
// `import … with { type: 'file' }`. So we (1) build the web + workspace bundles,
// (2) GENERATE scripts/build-manifest.ts with one such import per web asset +
// migration .sql + the journal, then (3) compile index.ts (whose import graph —
// index -> app/auto-migrate -> build-manifest — reaches every `type: 'file'`
// import). At runtime app.ts / auto-migrate.ts read the embedded paths from the
// manifest when Bun.embeddedFiles.length > 0.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { $ } from 'bun';

const repoRoot = path.resolve(import.meta.dir, '..');
const webDist = path.join(repoRoot, 'apps/web/dist');
const migrationsDir = path.join(repoRoot, 'apps/server/src/db/migrations');
const manifestPath = path.join(repoRoot, 'scripts/build-manifest.ts');

// 1. Build web + every workspace via the existing root `build` script.
console.log('[build] building workspaces (web + others)…');
await $`bun run build`.cwd(repoRoot);

// 2a. Walk apps/web/dist recursively; key each asset by its request pathname.
function walk(dir: string, out: string[]): void {
  for (const entry of readdirSync(dir)) {
    const abs = path.join(dir, entry);
    if (statSync(abs).isDirectory()) {
      walk(abs, out);
    } else {
      out.push(abs);
    }
  }
}
const webFiles: string[] = [];
walk(webDist, webFiles);
webFiles.sort();
// Request pathname is the POSIX-relative path from dist root with a leading '/'.
const webAssets = webFiles.map((abs) => ({
  abs,
  reqPath: `/${path.relative(webDist, abs).split(path.sep).join('/')}`,
}));

// 2b. Migration .sql files + the journal.
const migrationFiles = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();
const journalAbs = path.join(migrationsDir, 'meta', '_journal.json');

// 2c. Generate the manifest with `with { type: 'file' }` imports (absolute paths,
// so --compile resolves them regardless of cwd). The imported binding is the
// embedded file PATH Bun hands back at runtime. Emit SINGLE-quoted string
// literals so the generated file already satisfies the repo's Biome
// quoteStyle:single — the manifest must never depend on a lint accident to stay
// out of a commit; the pre-commit-build-manifest hook is the real guard.
const sq = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const lines: string[] = [];
lines.push('// GENERATED by scripts/build.ts — do not edit; rewritten every build:binary.');
lines.push('// Committed stub (empty records) is restored by `git checkout` for dev.');
lines.push('');

webAssets.forEach((a, i) => {
  lines.push(`import web${i} from ${sq(a.abs)} with { type: 'file' };`);
});
migrationFiles.forEach((f, i) => {
  lines.push(`import mig${i} from ${sq(path.join(migrationsDir, f))} with { type: 'file' };`);
});
lines.push(`import journal from ${sq(journalAbs)} with { type: 'file' };`);
lines.push('');

lines.push('export const WEB_ASSETS: Record<string, string> = {');
webAssets.forEach((a, i) => {
  lines.push(`  ${sq(a.reqPath)}: web${i},`);
});
lines.push('};');
lines.push('');

lines.push('export const MIGRATIONS: Record<string, string> = {');
migrationFiles.forEach((f, i) => {
  lines.push(`  ${sq(f)}: mig${i},`);
});
lines.push('};');
lines.push('');
lines.push('export const JOURNAL_PATH = journal;');
lines.push('');

writeFileSync(manifestPath, `${lines.join('\n')}`);
console.log(
  `[build] manifest: ${webAssets.length} web asset(s), ${migrationFiles.length} migration(s) + journal`,
);

// 3. Compile. index.ts -> app.ts/auto-migrate.ts -> build-manifest.ts pulls every
// `with { type: 'file' }` import into the embed graph.
console.log('[build] compiling dist/folio…');
await $`bun build apps/server/src/index.ts --compile --outfile dist/folio`.cwd(repoRoot);

console.log('[build] done → dist/folio');
