#!/usr/bin/env bash
# Installs the project's pre-commit hooks into .git/hooks/.
# Safe to re-run; replaces any existing pre-commit hook.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DST="$REPO_ROOT/.git/hooks/pre-commit"
HOOK_SRC_DIR="$REPO_ROOT/scripts/hooks"

cat > "$HOOK_DST" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/hooks/install.sh — do not edit by hand.
set -e
"$HOOK_SRC_DIR/pre-commit-migration-journal.sh"
EOF
chmod +x "$HOOK_DST"
echo "installed: $HOOK_DST"
